import 'package:mytradeasia/features/domain/entities/sales_force_data_entities/sales_force_cp_entity.dart';

class SalesforceCPModel extends SalesforceCPEntity {
  int? totalSize;
  bool? done;
  List<CPRecords>? records;

  SalesforceCPModel({this.totalSize, this.done, this.records});

  SalesforceCPModel.fromJson(Map<String, dynamic> json) {
    totalSize = json['totalSize'];
    done = json['done'];
    if (json['records'] != null) {
      records = <CPRecords>[];
      json['records'].forEach((v) {
        records!.add(new CPRecords.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['totalSize'] = this.totalSize;
    data['done'] = this.done;
    if (this.records != null) {
      data['records'] = this.records!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class CPRecords {
  Attributes? attributes;
  String? id;
  String? createdById;
  String? lastModifiedById;
  String? opportunityC;
  String? x1stSectorBLNoC;
  String? sailingOnAboutC;
  String? remarksC;
  double? quantityC;
  String? uOMC;
  String? productNameC;
  double? unitPriceUOMC;
  double? totalPriceC;
  String? invNoC;
  String? invDateC;
  String? bLNoC;
  String? shipperBankC;
  String? vesselVOYNoC;
  String? descriptionOfGoodsC;
  String? pINoC;
  String? remarksPackingListC;
  String? accountNameBackendC;
  String? consignedSoldToC;
  String? applicantNameAndAddressC;
  dynamic packingListC;
  String? bLDateC;
  String? authorizedSignatoryC;
  dynamic draweeC;
  dynamic freightChargesSIC;
  String? remarksPLC;
  String? countryOfOriginC;
  double? quantityPerContainerC;
  double? totalOfContainersC;
  String? cIC;
  String? eTAEstimatedDateOfArrivalC;
  String? bookingNmbrAutoC;
  double? amountInsuredC;
  double? rateC;
  double? premiumAmountC;
  double? stampDutyC;
  double? totalInsuranceAmountC;
  String? containerSizeC;
  String? vesselLabelC;
  String? totalPriceWordsC;
  bool? acceptanceC;
  String? countryOfFinalDestinationC;
  String? tenorC;
  String? businessEntityC;
  String? sUBJECTForShippingAdviseC;
  String? workedByC;
  String? sTATUSC;
  String? aWBNOC;
  String? bLAutoGeneratedNumberC;
  String? statusDealC;
  double? totalAdvancePaymentC;
  double? totalAMOUNTIncludngAllChargesC;
  double? amountAfterReducingAdvanceC;
  String? accountC;
  String? xeroDescC;
  String? paymentStatusC;
  String? bankAccountC;
  String? bankReferenceNoC;
  String? remarksForFinancingC;
  double? interestAmountC;
  double? receivedAmountC;
  double? discountedAmountC;
  String? receivedDateC;
  double? balanceAmountC;
  double? creditLimitC;
  double? taxC;
  String? totalPriceINRWordsC;
  bool? withHouseBLNoC;
  String? accountAddressC;
  String? todayC;
  double? totalAgentCommissionC;
  double? totalBrokerageChargeC;
  String? indicativeDueDateC;
  double? amountAfterDeductingAdvanceC;
  String? carrierNameC;
  double? totalAmountExcludingTaxC;
  String? totalAmountInclTaxInWordsC;
  double? totalAmountAfterTaxC;
  double? taxAmountBackendC;
  double? totalAMOUNTIncludingAllChargesBacC;
  double? overDueDaysIndonesiaC;
  String? dueDateC;
  double? remainingPaymentC;
  double? lateDaysC;
  double? totalPurchaseC;
  double? totalPurchasePriceC;
  double? totalPurchaseSOC;
  String? aWBServiceC;
  double? profitMarginC;
  String? aWBOriginAddressC;
  String? aWBDestinationAddressC;
  String? aWBCurrentStatusC;
  String? aWBCurrentLocationC;
  String? aWBStatusDescriptionC;
  String? aWBLastStatusUpdatedC;

  CPRecords(
      {this.attributes,
      this.id,
      this.createdById,
      this.lastModifiedById,
      this.opportunityC,
      this.x1stSectorBLNoC,
      this.sailingOnAboutC,
      this.remarksC,
      this.quantityC,
      this.uOMC,
      this.productNameC,
      this.unitPriceUOMC,
      this.totalPriceC,
      this.invNoC,
      this.invDateC,
      this.bLNoC,
      this.shipperBankC,
      this.vesselVOYNoC,
      this.descriptionOfGoodsC,
      this.pINoC,
      this.remarksPackingListC,
      this.accountNameBackendC,
      this.consignedSoldToC,
      this.applicantNameAndAddressC,
      this.packingListC,
      this.bLDateC,
      this.authorizedSignatoryC,
      this.draweeC,
      this.freightChargesSIC,
      this.remarksPLC,
      this.countryOfOriginC,
      this.quantityPerContainerC,
      this.totalOfContainersC,
      this.cIC,
      this.eTAEstimatedDateOfArrivalC,
      this.bookingNmbrAutoC,
      this.amountInsuredC,
      this.rateC,
      this.premiumAmountC,
      this.stampDutyC,
      this.totalInsuranceAmountC,
      this.containerSizeC,
      this.vesselLabelC,
      this.totalPriceWordsC,
      this.acceptanceC,
      this.countryOfFinalDestinationC,
      this.tenorC,
      this.businessEntityC,
      this.sUBJECTForShippingAdviseC,
      this.workedByC,
      this.sTATUSC,
      this.aWBNOC,
      this.bLAutoGeneratedNumberC,
      this.statusDealC,
      this.totalAdvancePaymentC,
      this.totalAMOUNTIncludngAllChargesC,
      this.amountAfterReducingAdvanceC,
      this.accountC,
      this.xeroDescC,
      this.paymentStatusC,
      this.bankAccountC,
      this.bankReferenceNoC,
      this.remarksForFinancingC,
      this.interestAmountC,
      this.receivedAmountC,
      this.discountedAmountC,
      this.receivedDateC,
      this.balanceAmountC,
      this.creditLimitC,
      this.taxC,
      this.totalPriceINRWordsC,
      this.withHouseBLNoC,
      this.accountAddressC,
      this.todayC,
      this.totalAgentCommissionC,
      this.totalBrokerageChargeC,
      this.indicativeDueDateC,
      this.amountAfterDeductingAdvanceC,
      this.carrierNameC,
      this.totalAmountExcludingTaxC,
      this.totalAmountInclTaxInWordsC,
      this.totalAmountAfterTaxC,
      this.taxAmountBackendC,
      this.totalAMOUNTIncludingAllChargesBacC,
      this.overDueDaysIndonesiaC,
      this.dueDateC,
      this.remainingPaymentC,
      this.lateDaysC,
      this.totalPurchaseC,
      this.totalPurchasePriceC,
      this.totalPurchaseSOC,
      this.aWBServiceC,
      this.profitMarginC,
      this.aWBOriginAddressC,
      this.aWBDestinationAddressC,
      this.aWBCurrentStatusC,
      this.aWBCurrentLocationC,
      this.aWBStatusDescriptionC,
      this.aWBLastStatusUpdatedC});

  CPRecords.fromJson(Map<String, dynamic> json) {
    attributes = json['attributes'] != null
        ? new Attributes.fromJson(json['attributes'])
        : null;
    id = json['Id'];
    createdById = json['CreatedById'];
    lastModifiedById = json['LastModifiedById'];
    opportunityC = json['Opportunity__c'];
    x1stSectorBLNoC = json['X1st_Sector_BL_No__c'];
    sailingOnAboutC = json['Sailing_On_About__c'];
    remarksC = json['Remarks__c'];
    quantityC = json['Quantity__c'];
    uOMC = json['UOM__c'];
    productNameC = json['Product_Name__c'];
    unitPriceUOMC = json['Unit_Price_UOM__c'];
    totalPriceC = json['Total_Price__c'];
    invNoC = json['Inv_No__c'];
    invDateC = json['Inv_Date__c'];
    bLNoC = json['B_L_No__c'];
    shipperBankC = json['Shipper_Bank__c'];
    vesselVOYNoC = json['Vessel_VOY_No__c'];
    descriptionOfGoodsC = json['Description_of_Goods__c'];
    pINoC = json['PI_No__c'];
    remarksPackingListC = json['Remarks_Packing_List__c'];
    accountNameBackendC = json['Account_Name_Backend__c'];
    consignedSoldToC = json['Consigned_Sold_To__c'];
    applicantNameAndAddressC = json['Applicant_Name_and_Address__c'];
    packingListC = json['Packing_List__c'];
    bLDateC = json['B_L_Date__c'];
    authorizedSignatoryC = json['Authorized_Signatory__c'];
    draweeC = json['Drawee__c'];
    freightChargesSIC = json['Freight_Charges_SI__c'];
    remarksPLC = json['Remarks_PL__c'];
    countryOfOriginC = json['Country_of_Origin__c'];
    quantityPerContainerC = json['Quantity_Per_Container__c'];
    totalOfContainersC = json['Total_of_Containers__c'];
    cIC = json['CI__c'];
    eTAEstimatedDateOfArrivalC = json['ETA_estimated_Date_of_Arrival__c'];
    bookingNmbrAutoC = json['Booking_Nmbr_auto__c'];
    amountInsuredC = json['Amount_Insured__c'];
    rateC = json['Rate__c'];
    premiumAmountC = json['Premium_Amount__c'];
    stampDutyC = json['Stamp_Duty__c'];
    totalInsuranceAmountC = json['Total_Insurance_Amount__c'];
    containerSizeC = json['Container_Size__c'];
    vesselLabelC = json['Vessel_Label__c'];
    totalPriceWordsC = json['Total_Price_words__c'];
    acceptanceC = json['Acceptance__c'];
    countryOfFinalDestinationC = json['Country_of_Final_Destination__c'];
    tenorC = json['Tenor__c'];
    businessEntityC = json['Business_Entity__c'];
    sUBJECTForShippingAdviseC = json['SUBJECT_For_Shipping_Advise__c'];
    workedByC = json['Worked_By__c'];
    sTATUSC = json['STATUS__c'];
    aWBNOC = json['AWB_NO__c'];
    bLAutoGeneratedNumberC = json['BL_Auto_generated_Number__c'];
    statusDealC = json['Status_Deal__c'];
    totalAdvancePaymentC = json['Total_Advance_Payment__c'];
    totalAMOUNTIncludngAllChargesC =
        json['Total_AMOUNT_includng_all_charges__c'];
    amountAfterReducingAdvanceC = json['Amount_after_reducing_advance__c'];
    accountC = json['Account__c'];
    xeroDescC = json['Xero_Desc__c'];
    paymentStatusC = json['Payment_Status__c'];
    bankAccountC = json['Bank_Account__c'];
    bankReferenceNoC = json['Bank_Reference_No__c'];
    remarksForFinancingC = json['Remarks_for_Financing__c'];
    interestAmountC = json['Interest_Amount__c'];
    receivedAmountC = json['Received_Amount__c'];
    discountedAmountC = json['Discounted_Amount__c'];
    receivedDateC = json['Received_Date__c'];
    balanceAmountC = json['Balance_Amount__c'];
    creditLimitC = json['Credit_Limit__c'];
    taxC = json['Tax__c'];
    totalPriceINRWordsC = json['Total_Price_INR_words__c'];
    withHouseBLNoC = json['With_House_B_L_No__c'];
    accountAddressC = json['Account_Address__c'];
    todayC = json['Today__c'];
    totalAgentCommissionC = json['Total_Agent_Commission__c'];
    totalBrokerageChargeC = json['Total_Brokerage_Charge__c'];
    indicativeDueDateC = json['Indicative_Due_Date__c'];
    amountAfterDeductingAdvanceC = json['Amount_after_deducting_advance__c'];
    carrierNameC = json['Carrier_Name__c'];
    totalAmountExcludingTaxC = json['Total_Amount_Excluding_Tax__c'];
    totalAmountInclTaxInWordsC = json['Total_Amount_incl_Tax_In_Words__c'];
    totalAmountAfterTaxC = json['Total_amount_after_tax__c'];
    taxAmountBackendC = json['Tax_Amount_Backend__c'];
    totalAMOUNTIncludingAllChargesBacC =
        json['Total_AMOUNT_including_all_charges_Bac__c'];
    overDueDaysIndonesiaC = json['OverDue_Days_Indonesia__c'];
    dueDateC = json['Due_Date__c'];
    remainingPaymentC = json['Remaining_Payment__c'];
    lateDaysC = json['Late_Days__c'];
    totalPurchaseC = json['Total_Purchase__c'];
    totalPurchasePriceC = json['Total_Purchase_Price__c'];
    totalPurchaseSOC = json['Total_Purchase_SO__c'];
    aWBServiceC = json['AWB_Service__c'];
    profitMarginC = json['Profit_Margin__c'];
    aWBOriginAddressC = json['AWB_Origin_Address__c'];
    aWBDestinationAddressC = json['AWB_Destination_Address__c'];
    aWBCurrentStatusC = json['AWB_Current_Status__c'];
    aWBCurrentLocationC = json['AWB_Current_Location__c'];
    aWBStatusDescriptionC = json['AWB_Status_Description__c'];
    aWBLastStatusUpdatedC = json['AWB_Last_Status_Updated__c'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.attributes != null) {
      data['attributes'] = this.attributes!.toJson();
    }
    data['Id'] = this.id;
    data['CreatedById'] = this.createdById;
    data['LastModifiedById'] = this.lastModifiedById;
    data['Opportunity__c'] = this.opportunityC;
    data['X1st_Sector_BL_No__c'] = this.x1stSectorBLNoC;
    data['Sailing_On_About__c'] = this.sailingOnAboutC;
    data['Remarks__c'] = this.remarksC;
    data['Quantity__c'] = this.quantityC;
    data['UOM__c'] = this.uOMC;
    data['Product_Name__c'] = this.productNameC;
    data['Unit_Price_UOM__c'] = this.unitPriceUOMC;
    data['Total_Price__c'] = this.totalPriceC;
    data['Inv_No__c'] = this.invNoC;
    data['Inv_Date__c'] = this.invDateC;
    data['B_L_No__c'] = this.bLNoC;
    data['Shipper_Bank__c'] = this.shipperBankC;
    data['Vessel_VOY_No__c'] = this.vesselVOYNoC;
    data['Description_of_Goods__c'] = this.descriptionOfGoodsC;
    data['PI_No__c'] = this.pINoC;
    data['Remarks_Packing_List__c'] = this.remarksPackingListC;
    data['Account_Name_Backend__c'] = this.accountNameBackendC;
    data['Consigned_Sold_To__c'] = this.consignedSoldToC;
    data['Applicant_Name_and_Address__c'] = this.applicantNameAndAddressC;
    data['Packing_List__c'] = this.packingListC;
    data['B_L_Date__c'] = this.bLDateC;
    data['Authorized_Signatory__c'] = this.authorizedSignatoryC;
    data['Drawee__c'] = this.draweeC;
    data['Freight_Charges_SI__c'] = this.freightChargesSIC;
    data['Remarks_PL__c'] = this.remarksPLC;
    data['Country_of_Origin__c'] = this.countryOfOriginC;
    data['Quantity_Per_Container__c'] = this.quantityPerContainerC;
    data['Total_of_Containers__c'] = this.totalOfContainersC;
    data['CI__c'] = this.cIC;
    data['ETA_estimated_Date_of_Arrival__c'] = this.eTAEstimatedDateOfArrivalC;
    data['Booking_Nmbr_auto__c'] = this.bookingNmbrAutoC;
    data['Amount_Insured__c'] = this.amountInsuredC;
    data['Rate__c'] = this.rateC;
    data['Premium_Amount__c'] = this.premiumAmountC;
    data['Stamp_Duty__c'] = this.stampDutyC;
    data['Total_Insurance_Amount__c'] = this.totalInsuranceAmountC;
    data['Container_Size__c'] = this.containerSizeC;
    data['Vessel_Label__c'] = this.vesselLabelC;
    data['Total_Price_words__c'] = this.totalPriceWordsC;
    data['Acceptance__c'] = this.acceptanceC;
    data['Country_of_Final_Destination__c'] = this.countryOfFinalDestinationC;
    data['Tenor__c'] = this.tenorC;
    data['Business_Entity__c'] = this.businessEntityC;
    data['SUBJECT_For_Shipping_Advise__c'] = this.sUBJECTForShippingAdviseC;
    data['Worked_By__c'] = this.workedByC;
    data['STATUS__c'] = this.sTATUSC;
    data['AWB_NO__c'] = this.aWBNOC;
    data['BL_Auto_generated_Number__c'] = this.bLAutoGeneratedNumberC;
    data['Status_Deal__c'] = this.statusDealC;
    data['Total_Advance_Payment__c'] = this.totalAdvancePaymentC;
    data['Total_AMOUNT_includng_all_charges__c'] =
        this.totalAMOUNTIncludngAllChargesC;
    data['Amount_after_reducing_advance__c'] = this.amountAfterReducingAdvanceC;
    data['Account__c'] = this.accountC;
    data['Xero_Desc__c'] = this.xeroDescC;
    data['Payment_Status__c'] = this.paymentStatusC;
    data['Bank_Account__c'] = this.bankAccountC;
    data['Bank_Reference_No__c'] = this.bankReferenceNoC;
    data['Remarks_for_Financing__c'] = this.remarksForFinancingC;
    data['Interest_Amount__c'] = this.interestAmountC;
    data['Received_Amount__c'] = this.receivedAmountC;
    data['Discounted_Amount__c'] = this.discountedAmountC;
    data['Received_Date__c'] = this.receivedDateC;
    data['Balance_Amount__c'] = this.balanceAmountC;
    data['Credit_Limit__c'] = this.creditLimitC;
    data['Tax__c'] = this.taxC;
    data['Total_Price_INR_words__c'] = this.totalPriceINRWordsC;
    data['With_House_B_L_No__c'] = this.withHouseBLNoC;
    data['Account_Address__c'] = this.accountAddressC;
    data['Today__c'] = this.todayC;
    data['Total_Agent_Commission__c'] = this.totalAgentCommissionC;
    data['Total_Brokerage_Charge__c'] = this.totalBrokerageChargeC;
    data['Indicative_Due_Date__c'] = this.indicativeDueDateC;
    data['Amount_after_deducting_advance__c'] =
        this.amountAfterDeductingAdvanceC;
    data['Carrier_Name__c'] = this.carrierNameC;
    data['Total_Amount_Excluding_Tax__c'] = this.totalAmountExcludingTaxC;
    data['Total_Amount_incl_Tax_In_Words__c'] = this.totalAmountInclTaxInWordsC;
    data['Total_amount_after_tax__c'] = this.totalAmountAfterTaxC;
    data['Tax_Amount_Backend__c'] = this.taxAmountBackendC;
    data['Total_AMOUNT_including_all_charges_Bac__c'] =
        this.totalAMOUNTIncludingAllChargesBacC;
    data['OverDue_Days_Indonesia__c'] = this.overDueDaysIndonesiaC;
    data['Due_Date__c'] = this.dueDateC;
    data['Remaining_Payment__c'] = this.remainingPaymentC;
    data['Late_Days__c'] = this.lateDaysC;
    data['Total_Purchase__c'] = this.totalPurchaseC;
    data['Total_Purchase_Price__c'] = this.totalPurchasePriceC;
    data['Total_Purchase_SO__c'] = this.totalPurchaseSOC;
    data['AWB_Service__c'] = this.aWBServiceC;
    data['Profit_Margin__c'] = this.profitMarginC;
    data['AWB_Origin_Address__c'] = this.aWBOriginAddressC;
    data['AWB_Destination_Address__c'] = this.aWBDestinationAddressC;
    data['AWB_Current_Status__c'] = this.aWBCurrentStatusC;
    data['AWB_Current_Location__c'] = this.aWBCurrentLocationC;
    data['AWB_Status_Description__c'] = this.aWBStatusDescriptionC;
    data['AWB_Last_Status_Updated__c'] = this.aWBLastStatusUpdatedC;
    return data;
  }
}

class Attributes {
  String? type;
  String? url;

  Attributes({this.type, this.url});

  Attributes.fromJson(Map<String, dynamic> json) {
    type = json['type'];
    url = json['url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['type'] = this.type;
    data['url'] = this.url;
    return data;
  }
}
